### ISSUE TITLE
Possible unwanted behavior with dependencies Node.js version support

### ISSUE THREAD

**Issue by darkgl0w** [fastify/github-action-merge-dependabot#144]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hello.

I just stumbled upon this on the `fastify-cli` repository :  https://github.com/fastify/fastify-cli/pull/449

__What is the issue ?__

The issue here is that since `dotenv@11.0.0` the minimum required Node.js version is  `>=12` while `fastify-cli` currently support Node.js 10 (note that there is no `{ "engines": { "node": ">=10" } }` in the `package.json` file, but the CI configuration trigger a run on Node.js 10).

And while `dotenv` officially support only Node.js 12 and greater they have not introduced any actual breaking change for now leading the CI to run without a single problem in `fastify-cli` repository.

**Comment by Eomm** [comment]
The issue is that the `target: minor` option is not set and by default the check is skipped.
Unfortunately, it is not set everywhere and it has done some unwanted merge across the fastify org.

On that repository, we should migrate to the new centralized workflow. Here is a reference:
https://github.com/fastify/fastify-autoload/pull/216
